# Generated by Django 3.2.15 on 2023-02-08 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего обновления'),
        ),
    ]
