# Generated by Django 3.2.15 on 2023-01-25 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230125_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
        ),
    ]
