# Generated by Django 3.2.15 on 2023-01-26 08:40

from django.db import migrations


def copy_price_to_order_items(apps, schema_editor):
    order_items = apps.get_model('foodcartapp', 'OrderItem')

    all_order_items = order_items.objects.all()

    for order_item in all_order_items.iterator():
        order_item.price = order_item.item.price


def cancel_copy_price(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_orderitem_item_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_order_items, cancel_copy_price),
    ]
