# Generated by Django 3.2.15 on 2023-01-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230126_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_price',
            new_name='price',
        ),
    ]
