# Generated by Django 3.2.15 on 2023-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AC', 'Accept'), ('AS', 'Assembly'), ('DE', 'Delivery'), ('CO', 'Complete')], default='AC', max_length=3, verbose_name='Статус заказа'),
        ),
    ]
