# Generated by Django 3.2.15 on 2023-01-31 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230131_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации заказа'),
        ),
    ]
