# Generated by Django 3.2.15 on 2023-01-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230131_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CA', 'Наличка'), ('EL', 'Электронно')], db_index=True, default='CA', max_length=3, verbose_name='Тип оплаты'),
        ),
    ]
