# Generated by Django 3.2.15 on 2023-02-03 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_order_production_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='production_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_restaurant', to='foodcartapp.restaurant', verbose_name='Заказ готовит ресторан'),
        ),
    ]
