# Generated by Django 3.2.15 on 2023-02-08 08:13

import django.core.validators
from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_production_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
        ),
    ]
