# Generated by Django 3.2.15 on 2023-02-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_auto_20230210_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CA', 'Наличка'), ('EL', 'Электронно'), ('DF', 'Не определено')], db_index=True, default='DF', max_length=3, verbose_name='Тип оплаты'),
        ),
    ]
